const _imageLinks = [
    'http://cdn.lovelife.vn/salt/media/093666b9a2c0250fa0291d2734731dd3.jpg',
    'http://cdn.lovelife.vn/salt/media/cbbd8bf92eaf4e17ce9532105a459125.jpg',
    'http://cdn.lovelife.vn/salt/media/f9155bd9ce4e8142c6d56e3f297a432f.png',
    'http://cdn.lovelife.vn/salt/media/dc6f01cd452cc87ef71287323fb0edc5.jpg'
];

//setting filter ....
const _categoryList = [{
    id: 1,
    categoryName: 'Thiết bị lọc'
}, {
    id: 2,
    categoryName: 'Máy lọc nước'
}, {
    id: 3,
    categoryName: 'Khác'
}]

const _productList = [{
    productName: 'Product 1',
    imgLink: 'https://salt.tikicdn.com/cache/280x280/ts/product/df/7d/da/d340edda2b0eacb7ddc47537cddb5e08.jpg',
    productPrice: '90,000 VND',
    categoryId: 1
}, {
    productName: 'Product 2',
    imgLink: 'https://salt.tikicdn.com/cache/280x280/ts/product/46/9d/eb/1795255d30e12f53d7a401e181abd0ec.jpg',
    productPrice: '46,000 VND',
    categoryId: 1
}, {
    productName: 'Product 2',
    imgLink: 'https://salt.tikicdn.com/cache/280x280/ts/product/98/36/6a/779ca1f7dba683aa53df8e259ddec52f.jpg',
    productPrice: '89,000 VND',
    categoryId: 2
}, {
    productName: 'Product 8',
    imgLink: 'https://salt.tikicdn.com/cache/280x280/ts/product/b3/1d/40/50430c9f6b9d159aa1df514c250b7b51.jpg',
    productPrice: '156,000 VND',
    categoryId: 2
}, {
    productName: 'Product 9',
    imgLink: 'https://salt.tikicdn.com/cache/280x280/ts/product/c2/93/76/3cca9f42b9d22dc75bed21c621aa652e.png',
    productPrice: '700,000 VND',
    categoryId: 3
}, {
    productName: 'Product 7',
    imgLink: 'https://salt.tikicdn.com/cache/280x280/ts/product/2b/ed/30/a9fb485f69abd35101f191c400ff75f6.JPG',
    productPrice: '400,000 VND',
    categoryId: 3
}, {
    productName: 'Product 10',
    imgLink: 'https://salt.tikicdn.com/cache/280x280/ts/product/33/e1/eb/675f9a58a2a2b96bd509dd0adc80fa3e.jpg',
    productPrice: '368,000 VND',
    categoryId: 3
}, {
    productName: 'Product 11',
    imgLink: 'https://salt.tikicdn.com/cache/280x280/ts/product/46/9d/eb/1795255d30e12f53d7a401e181abd0ec.jpg',
    productPrice: '200,000 VND',
    categoryId: 3
}];

const _productList2 = {
    "data": {
        "products": [{
            "name": "Máy lọc nước ChungHo Iguassu Ambient",
            "color": null,
            "description": null,
            "short_description": "Cung cấp nước tinh khiết với hệ thống lọc RO nguyên khối.\nSang trọng hiện đại với vòi lấy nước điện tử",
            "care_type": null,
            "attributes": null,
            "id": 24,
            "master_id": 24,
            "model": "CHP-1270D",
            "sku": null,
            "price": 7225000,
            "list_price": 8500000,
            "rent_price": 785000,
            "discount": 0,
            "discount_rate": 15,
            "is_visible": true,
            "is_rentable": true,
            "order_count": 0,
            "view_count": 0,
            "quantity_in_stock": 0,
            "sn_prefix": "Z11085",
            "care_type_id": 1,
            "supplier_id": 2,
            "point": 0,
            "created_at": 0,
            "updated_at": 1600791533805,
            "url_key": "may-loc-nuoc-chungho-iguassu-ambient",
            "url_path": "/may-loc-nuoc-chungho-iguassu-ambient-p24?pid=24",
            "thumbnail_url": "http://cdn.lovelife.vn/cache/250x250/u2unhO0Ee80cVAn2FKCFSViJC0tOMdQ1cCSd.jpg",
            "warranty_days": 360,
            "images": [],
            "supplier": null,
            "categoryId": 1
        },
        {
            "name": "Thiết bị lọc nước thương mại FX-15S",
            "color": null,
            "description": null,
            "short_description": "Thiết bị lọc nước sử dụng cho nấu ăn, pha chế ",
            "care_type": null,
            "attributes": null,
            "id": 94,
            "master_id": 0,
            "model": "FX-15S",
            "sku": null,
            "price": 5100000,
            "list_price": 6000000,
            "rent_price": 0,
            "discount": 0,
            "discount_rate": 0,
            "is_visible": true,
            "is_rentable": false,
            "order_count": 0,
            "view_count": 0,
            "quantity_in_stock": 0,
            "sn_prefix": null,
            "care_type_id": 1,
            "supplier_id": 2,
            "point": 255000,
            "created_at": 1595475970915,
            "updated_at": 1600791008502,
            "url_key": "thiet-bi-loc-nuoc-thuong-mai-fx-15s",
            "url_path": "/thiet-bi-loc-nuoc-thuong-mai-fx-15s-p94?pid=94",
            "thumbnail_url": "http://cdn.lovelife.vn/cache/250x250/242141fbf119eab0ff9b4fff9e9724a1.jpg",
            "warranty_days": 0,
            "images": [],
            "supplier": null,
            "categoryId": 1
        },
        {
            "name": "Thiết bị lọc nước thương mại FX-21S",
            "color": null,
            "description": null,
            "short_description": "Thiết bị lọc nước sử dụng cho nấu ăn, pha chế ",
            "care_type": null,
            "attributes": null,
            "id": 96,
            "master_id": 0,
            "model": "FX-21S",
            "sku": null,
            "price": 6300000,
            "list_price": 7000000,
            "rent_price": 0,
            "discount": 0,
            "discount_rate": 10,
            "is_visible": true,
            "is_rentable": false,
            "order_count": 0,
            "view_count": 0,
            "quantity_in_stock": 10,
            "sn_prefix": null,
            "care_type_id": 1,
            "supplier_id": 2,
            "point": 315000,
            "created_at": 1600790973078,
            "updated_at": 1600790995908,
            "url_key": "thiet-bi-loc-nuoc-thuong-mai-fx-21s",
            "url_path": "/thiet-bi-loc-nuoc-thuong-mai-fx-21s-p96?pid=96",
            "thumbnail_url": "http://cdn.lovelife.vn/cache/250x250/14ade7fdc10259985aed6f9cbf59e3c4.png",
            "warranty_days": 0,
            "images": [],
            "supplier": null,
            "categoryId": 1
        },
        {
            "name": "Máy lọc nước ChungHo Iguassu Ambient S",
            "color": null,
            "description": null,
            "short_description": "Tiện lợi hơn, Hiệu quả hơn, Tinh khiết hơn\nThiết kế siêu mỏng phù hợp với mọi không gian",
            "care_type": null,
            "attributes": null,
            "id": 23,
            "master_id": 23,
            "model": "CHP-1290D",
            "sku": null,
            "price": 5525000,
            "list_price": 6500000,
            "rent_price": 550000,
            "discount": 0,
            "discount_rate": 0,
            "is_visible": true,
            "is_rentable": true,
            "order_count": 0,
            "view_count": 0,
            "quantity_in_stock": 0,
            "sn_prefix": "Z11086",
            "care_type_id": 1,
            "supplier_id": 2,
            "point": 0,
            "created_at": 0,
            "updated_at": 1592365848568,
            "url_key": "may-loc-nuoc-chungho--iguassu-ambient-s",
            "url_path": "/may-loc-nuoc-chungho--iguassu-ambient-s-p23?pid=23",
            "thumbnail_url": "http://cdn.lovelife.vn/cache/250x250/08CRP3b6sGPpLot3etvNTpcpa6akFqwqCJQG.jpg",
            "warranty_days": 360,
            "images": [],
            "supplier": null,
            "categoryId": 1
        },
        {
            "name": "Chungho M9 Undersink",
            "color": null,
            "description": null,
            "short_description": "Cung cấp nước tinh khiết với hệ thống lõi lọc nguyên khối kết nối nhanh\nGọn gàng không gian bếp",
            "care_type": null,
            "attributes": null,
            "id": 22,
            "master_id": 22,
            "model": "M9 Undersink",
            "sku": null,
            "price": 7225000,
            "list_price": 8500000,
            "rent_price": 795000,
            "discount": 0,
            "discount_rate": 15,
            "is_visible": true,
            "is_rentable": false,
            "order_count": 0,
            "view_count": 0,
            "quantity_in_stock": 0,
            "sn_prefix": null,
            "care_type_id": 1,
            "supplier_id": 2,
            "point": 0,
            "created_at": 0,
            "updated_at": 1592365736146,
            "url_key": "chungho-m9-undersink",
            "url_path": "/chungho-m9-undersink-p22?pid=22",
            "thumbnail_url": "http://cdn.lovelife.vn/cache/250x250/Aa8gJywgY6MsXDrYmyHK6nApeiUr0q3PqF1B.jpg",
            "warranty_days": 360,
            "images": [],
            "supplier": null,
            "categoryId": 2
        },
        {
            "name": "Chungho U1",
            "color": null,
            "description": null,
            "short_description": "Máy lọc nước không sử dụng điện công suất cao",
            "care_type": null,
            "attributes": null,
            "id": 21,
            "master_id": 21,
            "model": "U1",
            "sku": null,
            "price": 5000000,
            "list_price": 5500000,
            "rent_price": 0,
            "discount": 0,
            "discount_rate": 0,
            "is_visible": true,
            "is_rentable": true,
            "order_count": 0,
            "view_count": 0,
            "quantity_in_stock": 0,
            "sn_prefix": null,
            "care_type_id": 1,
            "supplier_id": 2,
            "point": 250000,
            "created_at": 0,
            "updated_at": 1587576755232,
            "url_key": "chungho-u1",
            "url_path": "/chungho-u1-p21?pid=21",
            "thumbnail_url": "http://cdn.lovelife.vn/cache/250x250/VyNWDYpwNWWyWyK640VS0tu8JY7viBM81th9.jpg",
            "warranty_days": 360,
            "images": [],
            "supplier": null,
            "categoryId": 2
        },
        {
            "name": "Máy lọc nước ChungHo Iguassu 500 Plus",
            "color": null,
            "description": null,
            "short_description": "Tô điểm cho vẻ đẹp sang trọng của không gian sử dụng",
            "care_type": null,
            "attributes": null,
            "id": 29,
            "master_id": 29,
            "model": "CHP-3720S",
            "sku": null,
            "price": 20825000,
            "list_price": 24500000,
            "rent_price": 1000000,
            "discount": 0,
            "discount_rate": 15,
            "is_visible": true,
            "is_rentable": true,
            "order_count": 0,
            "view_count": 0,
            "quantity_in_stock": 0,
            "sn_prefix": "Z13556",
            "care_type_id": 1,
            "supplier_id": 2,
            "point": 0,
            "created_at": 0,
            "updated_at": 1587572540687,
            "url_key": "may-loc-nuoc-chungho--iguassu-500-plus",
            "url_path": "/may-loc-nuoc-chungho--iguassu-500-plus-p29?pid=29",
            "thumbnail_url": "http://cdn.lovelife.vn/cache/250x250/4reDYQ6IEj1aB1IJW1hjEsAUGqLnfjF8zepL.jpg",
            "warranty_days": 360,
            "images": [],
            "supplier": null,
            "categoryId": 2
        },
        {
            "name": "Máy lọc nước ChungHo IGUASSU DIGITAL",
            "color": null,
            "description": null,
            "short_description": "Công suất mạnh mẽ cho văn phòng và nhà xưởng\nCung cấp nước nóng, lạnh, thường cho nhu cầu sử dụng khoảng 60 người",
            "care_type": null,
            "attributes": null,
            "id": 28,
            "master_id": 28,
            "model": "CHP-3800ST",
            "sku": null,
            "price": 18800000,
            "list_price": 23500000,
            "rent_price": 1200000,
            "discount": 0,
            "discount_rate": 0,
            "is_visible": true,
            "is_rentable": true,
            "order_count": 0,
            "view_count": 0,
            "quantity_in_stock": 0,
            "sn_prefix": "Z13557",
            "care_type_id": 1,
            "supplier_id": 2,
            "point": 0,
            "created_at": 0,
            "updated_at": 1587572467908,
            "url_key": "may-loc-nuoc-chungho--iguassu-digital",
            "url_path": "/may-loc-nuoc-chungho--iguassu-digital-p28?pid=28",
            "thumbnail_url": "http://cdn.lovelife.vn/cache/250x250/0mYuinHHIMWNu95hBJL8Uxn4laGnUBAAD6jo.jpg",
            "warranty_days": 360,
            "images": [],
            "supplier": null,
            "categoryId": 2
        },
        {
            "name": "Máy lọc nước ChungHo New Whi Caffe 700",
            "color": null,
            "description": null,
            "short_description": "Thưởng thức hương vị cà phê Espresso - Italy cùng Whi Caffe",
            "care_type": null,
            "attributes": null,
            "id": 31,
            "master_id": 31,
            "model": "WF-70S9500M",
            "sku": null,
            "price": 34000000,
            "list_price": 42500000,
            "rent_price": 3990000,
            "discount": 0,
            "discount_rate": 20,
            "is_visible": true,
            "is_rentable": false,
            "order_count": 0,
            "view_count": 0,
            "quantity_in_stock": 0,
            "sn_prefix": "Z17129",
            "care_type_id": 1,
            "supplier_id": 2,
            "point": 0,
            "created_at": 0,
            "updated_at": 1583916914975,
            "url_key": "may-loc-nuoc-chungho--new-whi-caffe-700",
            "url_path": "/may-loc-nuoc-chungho--new-whi-caffe-700-p31?pid=31",
            "thumbnail_url": "http://cdn.lovelife.vn/cache/250x250/V9Y1qJWomnTv80KW2zpOaiqY7eJxCaXs2dvP.jpg",
            "warranty_days": 360,
            "images": [],
            "supplier": null,
            "categoryId": 2
        },
        {
            "name": "Máy lọc nước ChungHo Wine Cellar",
            "color": null,
            "description": null,
            "short_description": null,
            "care_type": null,
            "attributes": null,
            "id": 33,
            "master_id": 33,
            "model": "CHP-5150S",
            "sku": null,
            "price": 34500000,
            "list_price": 34500000,
            "rent_price": 3450000,
            "discount": 0,
            "discount_rate": 0,
            "is_visible": true,
            "is_rentable": true,
            "order_count": 0,
            "view_count": 0,
            "quantity_in_stock": 0,
            "sn_prefix": "Z10406",
            "care_type_id": 1,
            "supplier_id": 2,
            "point": 1725000,
            "created_at": 0,
            "updated_at": 1583915609930,
            "url_key": "may-loc-nuoc-chungho--wine-cellar",
            "url_path": "/may-loc-nuoc-chungho--wine-cellar-p33?pid=33",
            "thumbnail_url": "http://cdn.lovelife.vn/cache/250x250/MCLWZhv7YfhdA4bzDWkwborqOM5hRXyzQVjb.jpg",
            "warranty_days": 360,
            "images": [],
            "supplier": null,
            "categoryId": 2
        },
        {
            "name": "Máy lọc nước ChungHo Iguassu T-461",
            "color": null,
            "description": null,
            "short_description": "Sang trọng và quý phái\nVới 4 chức năng: Làm đá, Nóng, Lạnh và Thường",
            "care_type": null,
            "attributes": null,
            "id": 30,
            "master_id": 30,
            "model": "CHP-5170S",
            "sku": null,
            "price": 29800000,
            "list_price": 29800000,
            "rent_price": 2980000,
            "discount": 0,
            "discount_rate": 0,
            "is_visible": true,
            "is_rentable": false,
            "order_count": 0,
            "view_count": 0,
            "quantity_in_stock": 0,
            "sn_prefix": "Z10407",
            "care_type_id": 1,
            "supplier_id": 2,
            "point": 0,
            "created_at": 0,
            "updated_at": 1583915271353,
            "url_key": "may-loc-nuoc-chungho--iguassu-t-461",
            "url_path": "/may-loc-nuoc-chungho--iguassu-t-461-p30?pid=30",
            "thumbnail_url": "http://cdn.lovelife.vn/cache/250x250/2Ab6ReBtFP4gvtN27PqPKdeb8h6UiVvPaXhx.jpg",
            "warranty_days": 360,
            "images": [],
            "supplier": null,
            "categoryId": 2
        },
        {
            "name": "Chungho NEW 700 ICE",
            "color": null,
            "description": null,
            "short_description": "Công nghệ làm đá tiên tiến\nCuộc sống tiện lợi hơn an toàn hơn",
            "care_type": null,
            "attributes": null,
            "id": 32,
            "master_id": 32,
            "model": "CHP-5380S2",
            "sku": null,
            "price": 30000000,
            "list_price": 37500000,
            "rent_price": 1350000,
            "discount": 0,
            "discount_rate": 20,
            "is_visible": true,
            "is_rentable": true,
            "order_count": 0,
            "view_count": 0,
            "quantity_in_stock": 0,
            "sn_prefix": "Z10580",
            "care_type_id": 1,
            "supplier_id": 2,
            "point": 0,
            "created_at": 0,
            "updated_at": 1583914491081,
            "url_key": "chungho-new-700-ice",
            "url_path": "/chungho-new-700-ice-p32?pid=32",
            "thumbnail_url": "http://cdn.lovelife.vn/cache/250x250/s0S1uarKCxwvhXx77ZuyRmOSObo2VJeUgYeX.jpg",
            "warranty_days": 360,
            "images": [],
            "supplier": null,
            "categoryId": 3
        },
        {
            "name": "Máy lọc nước ChungHo Iguassu Tiny 900 ICE",
            "color": null,
            "description": null,
            "short_description": "Sang trọng, tinh tế, tiện lợi với chức năng nóng, lạnh, thường, đá trong một sản phẩm nhỏ gọn.",
            "care_type": null,
            "attributes": null,
            "id": 27,
            "master_id": 27,
            "model": "CHP-5321D",
            "sku": null,
            "price": 22525000,
            "list_price": 26500000,
            "rent_price": 1100000,
            "discount": 0,
            "discount_rate": 15,
            "is_visible": true,
            "is_rentable": true,
            "order_count": 0,
            "view_count": 0,
            "quantity_in_stock": 0,
            "sn_prefix": "Z10409",
            "care_type_id": 1,
            "supplier_id": 2,
            "point": 1126250,
            "created_at": 0,
            "updated_at": 1583914075632,
            "url_key": "may-loc-nuoc-chungho--iguassu-tiny-900-ice",
            "url_path": "/may-loc-nuoc-chungho--iguassu-tiny-900-ice-p27?pid=27",
            "thumbnail_url": "http://cdn.lovelife.vn/cache/250x250/8sTodiNZpqSS7DhSlkBbpjhglWF51XRjEpE0.jpg",
            "warranty_days": 360,
            "images": [],
            "supplier": null,
            "categoryId": 3
        },
        {
            "name": "Máy lọc nước ChungHo Iguassu Tiny",
            "color": null,
            "description": null,
            "short_description": "Tiện lợi với chức năng Nóng, Lạnh, Thường. Tất cả trong một sản phẩm",
            "care_type": null,
            "attributes": null,
            "id": 26,
            "master_id": 26,
            "model": "CHP-3931D",
            "sku": null,
            "price": 16575000,
            "list_price": 19500000,
            "rent_price": 850000,
            "discount": 0,
            "discount_rate": 15,
            "is_visible": true,
            "is_rentable": true,
            "order_count": 0,
            "view_count": 0,
            "quantity_in_stock": 0,
            "sn_prefix": "Z13255",
            "care_type_id": 1,
            "supplier_id": 2,
            "point": 828750,
            "created_at": 0,
            "updated_at": 1583911082600,
            "url_key": "may-loc-nuoc-chungho--iguassu-tiny",
            "url_path": "/may-loc-nuoc-chungho--iguassu-tiny-p26?pid=26",
            "thumbnail_url": "http://cdn.lovelife.vn/cache/250x250/wNi5WHjFutxThV4w4RC3Rn0gxpaelRHZOta7.jpg",
            "warranty_days": 360,
            "images": [],
            "supplier": null,
            "categoryId": 3
        },
        {
            "name": "Máy lọc nước ChungHo Iguassu Tiny",
            "color": null,
            "description": null,
            "short_description": "Cung cấp nước tinh khiết lạnh và thường.\nTinh khiết hơn với Hệ thống lọc RO nguyên khối kết hợp với Đèn UV diệt khuẩn.",
            "care_type": null,
            "attributes": null,
            "id": 25,
            "master_id": 25,
            "model": "CHP-2321D",
            "sku": null,
            "price": 13175000,
            "list_price": 15500000,
            "rent_price": 750000,
            "discount": 0,
            "discount_rate": 0,
            "is_visible": true,
            "is_rentable": true,
            "order_count": 0,
            "view_count": 0,
            "quantity_in_stock": 0,
            "sn_prefix": "Z12096",
            "care_type_id": 1,
            "supplier_id": 2,
            "point": 725000,
            "created_at": 0,
            "updated_at": 1583910666909,
            "url_key": "may-loc-nuoc-chungho--iguassu-tiny",
            "url_path": "/may-loc-nuoc-chungho--iguassu-tiny-p25?pid=25",
            "thumbnail_url": "http://cdn.lovelife.vn/cache/250x250/B8JiwhRMYIBNWVr9EgQbyHZvXBx76DQG82Qm.jpg",
            "warranty_days": 360,
            "images": [],
            "supplier": null,
            "categoryId": 3
        }
        ],
        "lastPage": true
    },
    "status": "OK"
}


export {
    _categoryList,
    _productList,
    _imageLinks,
    _productList2
}